### ISSUE TITLE
Multiple Applicants

### ISSUE THREAD

**Issue by topherreynoso** [vericred/vericred_ruby#2]
I love this gem for testing things on the fly and working in sandbox environments. Did you ever add support for multiple applicants in the plan search? I know this option exists in your documentation for the API. Any support here or an explanation on how it works?

**Comment by dlangevin** [comment]
Hey Topher,

We can do multiple applicants in a search.  Check out the following example for a 31yo non-smoker and a 42yo smoker:

```
Vericred::Plan.search(
  zip_code: '11215',
  fips_code: '36047',
  market: 'individual',
  applicants: [
    { age: 31 },
    { age: 42, smoker: true }
  ]
)
```

**Comment by dlangevin** [comment]
closing for tracking purposes - please re-open if it's not working for you

**Comment by topherreynoso** [comment]
Hey Dan, thanks for the response. I was not clear on my question. I was actually referring to being able to get premiums for a group (multiple employees). So the proposed solution would only give premiums for an individual or their family. Is there a way to add multiple employees that would not be in the same family quote and get a total premium for all of those individuals (or a return premium for each individual)?

**Comment by vericred-dev** [comment]
Oh I see - we don't support that in the API at the moment.  The challenge
there would be latency I think because a group could be quite large.  For
all states but VT and NY, you could just create a single "family" that
includes all of the covered individuals to get one price, but we would need
to do some work to

Is the use case just quoting through the API?  Or is there another use I'm
not thinking of?  Let me know and I will think through some options on how
we could do this in a more performant way.

**Comment by topherreynoso** [comment]
I think the solution of creating a "family" that includes everyone actually wouldn't work. It would max out on dependents at a certain number (in terms of affecting the premium) and currently it errors out when you have more than two adult (26+) members in the family.

It's really for testing more than anything else. I'd like to see how reliable we are on pricing. Currently we are interpreting your data and doing ratios on our end and I wanted to dig in a little and see what kind of reliability we can get on full quotes coming from Vericred data so that we could eventually eliminate the need to track and maintain that aspect on our side. Not a super high priority, I'm comfortable going forward with what we have, just thinking for the future.

**Comment by vericred-dev** [comment]
Yeah you are right - I didn't think about the limitations on number of
children who are quoted.

We do have some others doing full quotes through our API.  We're quite
confident on our age and smoking factors, and how they are applied to the
base rates we already provide you so it could be a good option if you
decide to go down that path.

For quoting a full group I would probably recommend us looking into a
background job that does the full calculation and pings you when it's ready
in some way.  Or just building it from a bunch of individual family quotes.

Happy to discuss further though if you like
